#!/usr/bin/env bun

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

export const GENERATED_HEADER = "Code generated by generate-contracts.ts; DO NOT EDIT.";

export interface AdminErrorCodeDefinition {
	code: number;
	name: string;
	reason: string;
}

export interface ProtocolCatalog {
	schemaVersion: number;
	operations: {
		host: string[];
		controller: string[];
	};
	thinkingLevels: string[];
	promptContentBlockTypes: string[];
	adminErrorCodes: AdminErrorCodeDefinition[];
}

export interface GeneratedArtifact {
	/** Repository-package-relative path, e.g. contracts/src/generated/protocol-catalog.ts. */
	path: string;
	content: string;
}

/** Schema path relative to the directory that contains package/package.json. */
export const SCHEMA_RELATIVE_PATH = "contracts/schema/protocol-catalog.json";

export const TYPESCRIPT_ARTIFACT_PATH = "contracts/src/generated/protocol-catalog.ts";
export const GO_ARTIFACT_PATH = "contracts/piprotocol/catalog_generated.go";

function fail(message: string): never {
	throw new Error(`protocol catalog: ${message}`);
}

function requireString(value: unknown, label: string): string {
	if (typeof value !== "string" || value === "") fail(`${label} must be a non-empty string`);
	return value;
}

function requireStringArray(value: unknown, label: string): string[] {
	if (!Array.isArray(value) || value.length === 0) fail(`${label} must be a non-empty array`);
	const result = value.map((entry, index) => requireString(entry, `${label}[${index}]`));
	if (new Set(result).size !== result.length) fail(`${label} contains duplicate values`);
	return result;
}

/** Validates the schema shape so a malformed edit fails generation instead of emitting partial artifacts. */
export function parseProtocolCatalog(raw: unknown): ProtocolCatalog {
	if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
		fail("schema root must be an object");
	}
	const record = raw as Record<string, unknown>;
	const schemaVersion = record.schemaVersion;
	if (
		typeof schemaVersion !== "number" ||
		!Number.isSafeInteger(schemaVersion) ||
		schemaVersion < 1
	) {
		fail("schemaVersion must be a positive integer");
	}
	const operations = record.operations;
	if (typeof operations !== "object" || operations === null || Array.isArray(operations)) {
		fail("operations must be an object");
	}
	const operationRecord = operations as Record<string, unknown>;
	const host = requireStringArray(operationRecord.host, "operations.host");
	const controller = requireStringArray(operationRecord.controller, "operations.controller");
	const thinkingLevels = requireStringArray(record.thinkingLevels, "thinkingLevels");
	const promptContentBlockTypes = requireStringArray(
		record.promptContentBlockTypes,
		"promptContentBlockTypes",
	);
	const rawErrors = record.adminErrorCodes;
	if (!Array.isArray(rawErrors) || rawErrors.length === 0) {
		fail("adminErrorCodes must be a non-empty array");
	}
	const codes = new Set<number>();
	const names = new Set<string>();
	const adminErrorCodes = rawErrors.map((entry, index) => {
		if (typeof entry !== "object" || entry === null || Array.isArray(entry)) {
			fail(`adminErrorCodes[${index}] must be an object`);
		}
		const errorRecord = entry as Record<string, unknown>;
		const code = errorRecord.code;
		if (typeof code !== "number" || !Number.isSafeInteger(code) || code >= 0) {
			fail(`adminErrorCodes[${index}].code must be a negative integer`);
		}
		const name = requireString(errorRecord.name, `adminErrorCodes[${index}].name`);
		const reason = requireString(errorRecord.reason, `adminErrorCodes[${index}].reason`);
		if (codes.has(code)) fail(`adminErrorCodes contains duplicate code ${code}`);
		if (names.has(name)) fail(`adminErrorCodes contains duplicate name ${name}`);
		codes.add(code);
		names.add(name);
		return { code, name, reason };
	});
	return {
		schemaVersion,
		operations: { host, controller },
		thinkingLevels,
		promptContentBlockTypes,
		adminErrorCodes,
	};
}

export function loadProtocolCatalog(schemaPath: string): ProtocolCatalog {
	let text: string;
	try {
		text = readFileSync(schemaPath, "utf8");
	} catch (error) {
		fail(`cannot read ${schemaPath}: ${(error as Error).message}`);
	}
	try {
		return parseProtocolCatalog(JSON.parse(text));
	} catch (error) {
		if (error instanceof SyntaxError) fail(`invalid JSON in ${schemaPath}: ${error.message}`);
		throw error;
	}
}

function stringLiteralList(values: readonly string[], indent = "\t"): string {
	return values.map((value) => `${indent}${JSON.stringify(value)},`).join("\n");
}

/** Matches Biome's formatting: collapse to one line when it fits within the 100-column budget. */
function renderExportedStringArray(name: string, values: readonly string[]): string {
	const inline = `export const ${name} = [${values.map((value) => JSON.stringify(value)).join(", ")}] as const;`;
	if (inline.length <= 100) return inline;
	return [`export const ${name} = [`, stringLiteralList(values), "] as const;"].join("\n");
}

function goStringBoolMap(values: readonly string[], indent = "\t"): string {
	const keys = values.map((value) => JSON.stringify(value));
	const width = Math.max(...keys.map((key) => key.length));
	return keys.map((key) => `${indent}${key}:${" ".repeat(width - key.length + 1)}true,`).join("\n");
}

export function renderTypeScript(catalog: ProtocolCatalog): string {
	const { host, controller } = catalog.operations;
	return [
		`// ${GENERATED_HEADER}`,
		"",
		`export const PROTOCOL_CATALOG_SCHEMA_VERSION = ${catalog.schemaVersion};`,
		"",
		renderExportedStringArray("HOST_OPERATIONS", host),
		"",
		"export type HostOperation = (typeof HOST_OPERATIONS)[number];",
		"",
		renderExportedStringArray("CONTROLLER_METHODS", controller),
		"",
		"export type ControllerMethod = (typeof CONTROLLER_METHODS)[number];",
		"",
		renderExportedStringArray("THINKING_LEVELS", catalog.thinkingLevels),
		"",
		"export type CatalogThinkingLevel = (typeof THINKING_LEVELS)[number];",
		"",
		renderExportedStringArray("PROMPT_CONTENT_BLOCK_TYPES", catalog.promptContentBlockTypes),
		"",
		"export type PromptContentBlockType = (typeof PROMPT_CONTENT_BLOCK_TYPES)[number];",
		"",
		"export const ADMIN_ERROR_CODES = [",
		...catalog.adminErrorCodes.map(
			(entry) =>
				`\t{ code: ${entry.code}, name: ${JSON.stringify(entry.name)}, reason: ${JSON.stringify(entry.reason)} },`,
		),
		"] as const;",
		"",
		'export type AdminErrorCode = (typeof ADMIN_ERROR_CODES)[number]["code"];',
		"",
	].join("\n");
}

export function renderGo(catalog: ProtocolCatalog): string {
	const { host, controller } = catalog.operations;
	return [
		`// ${GENERATED_HEADER}`,
		"",
		"package piprotocol",
		"",
		"// CatalogSchemaVersion is the protocol catalog schema revision.",
		`const CatalogSchemaVersion = ${catalog.schemaVersion}`,
		"",
		"// CatalogHostOperations lists the exact host native operation keys advertised by operationSet.",
		"var CatalogHostOperations = []string{",
		stringLiteralList(host),
		"}",
		"",
		"// CatalogHostOperationSet indexes CatalogHostOperations for exact lookup.",
		"var CatalogHostOperationSet = map[string]bool{",
		goStringBoolMap(host),
		"}",
		"",
		"// CatalogControllerMethods lists the browser/controller method names from ws-protocol.ts.",
		"var CatalogControllerMethods = []string{",
		stringLiteralList(controller),
		"}",
		"",
		"// CatalogThinkingLevels lists the accepted thinking levels.",
		"var CatalogThinkingLevels = []string{",
		stringLiteralList(catalog.thinkingLevels),
		"}",
		"",
		"// CatalogPromptContentBlockTypes lists the accepted prompt content block types.",
		"var CatalogPromptContentBlockTypes = []string{",
		stringLiteralList(catalog.promptContentBlockTypes),
		"}",
		"",
		"// CatalogAdminError is a versioned admin error code.",
		"type CatalogAdminError struct {",
		"\tCode   int",
		"\tName   string",
		"\tReason string",
		"}",
		"",
		"// CatalogAdminErrorCodes lists the versioned admin error codes used by the host.",
		"var CatalogAdminErrorCodes = []CatalogAdminError{",
		...catalog.adminErrorCodes.map(
			(entry) =>
				`\t{Code: ${entry.code}, Name: ${JSON.stringify(entry.name)}, Reason: ${JSON.stringify(entry.reason)}},`,
		),
		"}",
		"",
	].join("\n");
}

export function buildArtifacts(catalog: ProtocolCatalog): GeneratedArtifact[] {
	return [
		{ path: TYPESCRIPT_ARTIFACT_PATH, content: renderTypeScript(catalog) },
		{ path: GO_ARTIFACT_PATH, content: renderGo(catalog) },
	];
}

export function writeArtifacts(baseDir: string, artifacts: readonly GeneratedArtifact[]): void {
	for (const artifact of artifacts) {
		const target = resolve(baseDir, artifact.path);
		mkdirSync(dirname(target), { recursive: true });
		writeFileSync(target, artifact.content);
	}
}

/** Directory that contains package/package.json. */
export function defaultPackageDir(): string {
	return resolve(import.meta.dir, "..");
}

export function generateContracts(packageDir = defaultPackageDir()): GeneratedArtifact[] {
	const catalog = loadProtocolCatalog(resolve(packageDir, SCHEMA_RELATIVE_PATH));
	return buildArtifacts(catalog);
}

if (import.meta.main) {
	const packageDir = defaultPackageDir();
	const artifacts = generateContracts(packageDir);
	writeArtifacts(packageDir, artifacts);
	for (const artifact of artifacts) console.log(`generate-contracts: wrote ${artifact.path}`);
}
