#!/usr/bin/env bun

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

export const GENERATED_HEADER = "Code generated by generate-contracts.ts; DO NOT EDIT.";

export interface AdminErrorCodeDefinition {
	code: number;
	name: string;
	reason: string;
}

export type HostOperationStatus = "available" | "unavailable" | "absent";

export const HOST_OPERATION_STATUSES: readonly HostOperationStatus[] = [
	"available",
	"unavailable",
	"absent",
];

export interface HostOperationDefinition {
	name: string;
	status: HostOperationStatus;
	reason?: string;
}

export interface NativeRoutes {
	controller: string[];
	workspace: string[];
}

export interface OwnershipDefinition {
	method: string;
	fc: string;
	owner: string;
	profile: string;
	route: string;
	status?: HostOperationStatus;
	reason?: string;
}

export interface MethodFieldSchema {
	name: string;
	type: string;
	optional?: boolean;
}

export interface MethodSchema {
	name: string;
	params: MethodFieldSchema[];
	result: MethodFieldSchema[];
}

export interface ProtocolCatalog {
	schemaVersion: number;
	operations: {
		host: HostOperationDefinition[];
		controller: string[];
	};
	nativeRoutes: NativeRoutes;
	ownership: OwnershipDefinition[];
	methodSchemas: {
		host: MethodSchema[];
		controller: MethodSchema[];
	};
	thinkingLevels: string[];
	promptContentBlockTypes: string[];
	adminErrorCodes: AdminErrorCodeDefinition[];
}

const OWNERS = ["controller", "workspace", "pi"] as const;
const OWNER_SET = new Set<string>(OWNERS);
export const METHOD_FIELD_TYPES = ["string", "number", "boolean", "object", "array"] as const;
const METHOD_FIELD_TYPE_SET = new Set<string>(METHOD_FIELD_TYPES);

export interface GeneratedArtifact {
	/** Shared-module-relative path, e.g. src/generated/protocol-catalog.ts. */
	path: string;
	content: string;
}

/** Schema path relative to the directory that contains shared/package.json. */
export const SCHEMA_RELATIVE_PATH = "schema/protocol-catalog.json";

export const TYPESCRIPT_ARTIFACT_PATH = "src/generated/protocol-catalog.ts";
export const GO_ARTIFACT_PATH = "piprotocol/catalog_generated.go";

function fail(message: string): never {
	throw new Error(`protocol catalog: ${message}`);
}

function requireString(value: unknown, label: string): string {
	if (typeof value !== "string" || value === "") fail(`${label} must be a non-empty string`);
	return value;
}

function requireStringArray(value: unknown, label: string): string[] {
	if (!Array.isArray(value) || value.length === 0) fail(`${label} must be a non-empty array`);
	const result = value.map((entry, index) => requireString(entry, `${label}[${index}]`));
	if (new Set(result).size !== result.length) fail(`${label} contains duplicate values`);
	return result;
}

function isHostOperationStatus(value: unknown): value is HostOperationStatus {
	return (
		typeof value === "string" && (HOST_OPERATION_STATUSES as readonly string[]).includes(value)
	);
}

/**
 * Host operations carry an explicit implementation status. `available` routes
 * are the only ones a host may negotiate; `unavailable` and `absent` routes
 * stay catalogued so callers can fail closed with a stated reason.
 */
function parseHostOperations(value: unknown): HostOperationDefinition[] {
	if (!Array.isArray(value) || value.length === 0)
		fail("operations.host must be a non-empty array");
	const result: HostOperationDefinition[] = [];
	const names = new Set<string>();
	for (let index = 0; index < value.length; index += 1) {
		const entry = value[index];
		if (typeof entry !== "object" || entry === null || Array.isArray(entry)) {
			fail(`operations.host[${index}] must be an object`);
		}
		const record = entry as Record<string, unknown>;
		const name = requireString(record.name, `operations.host[${index}].name`);
		if (names.has(name)) fail(`operations.host contains duplicate operation ${name}`);
		names.add(name);
		if (!isHostOperationStatus(record.status)) {
			fail(`operations.host[${index}].status must be one of ${HOST_OPERATION_STATUSES.join(", ")}`);
		}
		if (record.status === "available") {
			if (record.reason !== undefined)
				fail(`operations.host[${index}] is available and must not carry a reason`);
			result.push({ name, status: record.status });
			continue;
		}
		const reason = requireString(record.reason, `operations.host[${index}].reason`);
		result.push({ name, status: record.status, reason });
	}
	return result;
}

function parseNativeRoutes(value: unknown): NativeRoutes {
	if (typeof value !== "object" || value === null || Array.isArray(value)) {
		fail("nativeRoutes must be an object");
	}
	const record = value as Record<string, unknown>;
	return {
		controller: requireStringArray(record.controller, "nativeRoutes.controller"),
		workspace: requireStringArray(record.workspace, "nativeRoutes.workspace"),
	};
}

function requireFc(value: unknown, label: string): string {
	const fc = requireString(value, label);
	if (!/^FC\d{2,}$/.test(fc)) fail(`${label} must look like FC08, got ${JSON.stringify(fc)}`);
	return fc;
}

/**
 * Validates one ownership row against the generated host statuses and the
 * declared native route namespaces. A row may only name a known native route,
 * and it must not advertise a host route the catalog marks absent or
 * unavailable as available. These checks are exported so contract tests can
 * prove that an unknown route or an over-advertised status fails.
 */
export function ownershipProblems(
	ownership: readonly OwnershipDefinition[],
	host: readonly HostOperationDefinition[],
	nativeRoutes: NativeRoutes,
): string[] {
	const hostStatus = new Map(host.map((entry) => [entry.name, entry.status]));
	const controllerRoutes = new Set(nativeRoutes.controller);
	const workspaceRoutes = new Set(nativeRoutes.workspace);
	const problems: string[] = [];
	const seen = new Set<string>();
	for (const entry of ownership) {
		if (entry.method === "") problems.push("ownership row has an empty method");
		if (seen.has(entry.method)) problems.push(`${entry.method}: duplicate ownership row`);
		seen.add(entry.method);
		if (!OWNER_SET.has(entry.owner)) {
			problems.push(`${entry.method}: unknown owner ${JSON.stringify(entry.owner)}`);
		}
		if (entry.route.startsWith("controller:")) {
			const id = entry.route.slice("controller:".length);
			if (!controllerRoutes.has(id)) {
				problems.push(`${entry.method}: unknown controller route ${entry.route}`);
			}
			if (entry.owner !== "controller") {
				problems.push(
					`${entry.method}: controller route ${entry.route} requires the controller owner`,
				);
			}
		} else if (entry.route.startsWith("workspace:")) {
			const id = entry.route.slice("workspace:".length);
			if (!workspaceRoutes.has(id)) {
				problems.push(`${entry.method}: unknown workspace route ${entry.route}`);
			}
			if (entry.owner !== "workspace") {
				problems.push(
					`${entry.method}: workspace route ${entry.route} requires the workspace owner`,
				);
			}
		} else {
			const status = hostStatus.get(entry.route);
			if (status === undefined) {
				problems.push(`${entry.method}: unknown native route ${entry.route}`);
			} else {
				if (entry.owner !== "pi") {
					problems.push(`${entry.method}: host route ${entry.route} requires the pi owner`);
				}
				if (entry.status !== undefined && entry.status !== status) {
					problems.push(
						`${entry.method}: declared status ${entry.status} disagrees with host status ${status} for ${entry.route}`,
					);
				}
				if (entry.status === "available" && status !== "available") {
					problems.push(
						`${entry.method}: advertises ${entry.route} as available but the host marks it ${status}`,
					);
				}
			}
		}
		if (entry.status === "available" && entry.reason !== undefined) {
			problems.push(`${entry.method}: an available route must not carry a reason`);
		}
		if (entry.status !== undefined && entry.status !== "available" && entry.reason === undefined) {
			problems.push(`${entry.method}: a non-available route requires a reason`);
		}
	}
	return problems;
}

function parseOwnership(value: unknown): OwnershipDefinition[] {
	if (!Array.isArray(value) || value.length === 0) fail("ownership must be a non-empty array");
	return value.map((entry, index) => {
		if (typeof entry !== "object" || entry === null || Array.isArray(entry)) {
			fail(`ownership[${index}] must be an object`);
		}
		const record = entry as Record<string, unknown>;
		const method = requireString(record.method, `ownership[${index}].method`);
		const owner = requireString(record.owner, `ownership[${index}].owner`);
		const route = requireString(record.route, `ownership[${index}].route`);
		const profile = requireString(record.profile, `ownership[${index}].profile`);
		const fc = requireFc(record.fc, `ownership[${index}].fc`);
		let status: HostOperationStatus | undefined;
		if (record.status !== undefined) {
			if (!isHostOperationStatus(record.status)) {
				fail(`ownership[${index}].status must be one of ${HOST_OPERATION_STATUSES.join(", ")}`);
			}
			status = record.status;
		}
		const parsed: OwnershipDefinition = { method, fc, owner, profile, route };
		if (status !== undefined) parsed.status = status;
		if (record.reason !== undefined) {
			parsed.reason = requireString(record.reason, `ownership[${index}].reason`);
		}
		return parsed;
	});
}

function parseMethodField(value: unknown, label: string): MethodFieldSchema {
	if (typeof value !== "object" || value === null || Array.isArray(value)) {
		fail(`${label} must be an object`);
	}
	const record = value as Record<string, unknown>;
	const name = requireString(record.name, `${label}.name`);
	const type = requireString(record.type, `${label}.type`);
	if (!METHOD_FIELD_TYPE_SET.has(type)) {
		fail(`${label}.type must be one of ${METHOD_FIELD_TYPES.join(", ")}`);
	}
	const field: MethodFieldSchema = { name, type };
	if (record.optional !== undefined) {
		if (typeof record.optional !== "boolean") fail(`${label}.optional must be a boolean`);
		field.optional = record.optional;
	}
	return field;
}

/**
 * Parses the method-level runtime schemas. Each entry declares the required
 * parameters and result fields for one method so the TypeScript and Go
 * adapters validate the same executable contract. Unknown fields are always
 * additive-compatible: only the declared fields are checked.
 */
function parseMethodSchemas(
	value: unknown,
	hostNames: readonly string[],
	controllerNames: readonly string[],
): { host: MethodSchema[]; controller: MethodSchema[] } {
	if (typeof value !== "object" || value === null || Array.isArray(value)) {
		fail("methodSchemas must be an object");
	}
	const record = value as Record<string, unknown>;
	const parseGroup = (group: unknown, label: string, known: readonly string[]): MethodSchema[] => {
		if (!Array.isArray(group) || group.length === 0) fail(`${label} must be a non-empty array`);
		const knownSet = new Set(known);
		const names = new Set<string>();
		return group.map((entry, index) => {
			const entryLabel = `${label}[${index}]`;
			if (typeof entry !== "object" || entry === null || Array.isArray(entry)) {
				fail(`${entryLabel} must be an object`);
			}
			const schemaRecord = entry as Record<string, unknown>;
			const name = requireString(schemaRecord.name, `${entryLabel}.name`);
			if (!knownSet.has(name)) fail(`${entryLabel}.name is not a catalogued method: ${name}`);
			if (names.has(name)) fail(`${label} contains duplicate method ${name}`);
			names.add(name);
			if (!Array.isArray(schemaRecord.params)) fail(`${entryLabel}.params must be an array`);
			if (!Array.isArray(schemaRecord.result)) fail(`${entryLabel}.result must be an array`);
			return {
				name,
				params: schemaRecord.params.map((field, fieldIndex) =>
					parseMethodField(field, `${entryLabel}.params[${fieldIndex}]`),
				),
				result: schemaRecord.result.map((field, fieldIndex) =>
					parseMethodField(field, `${entryLabel}.result[${fieldIndex}]`),
				),
			};
		});
	};
	return {
		host: parseGroup(record.host, "methodSchemas.host", hostNames),
		controller: parseGroup(record.controller, "methodSchemas.controller", controllerNames),
	};
}

/** Validates the schema shape so a malformed edit fails generation instead of emitting partial artifacts. */
export function parseProtocolCatalog(raw: unknown): ProtocolCatalog {
	if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
		fail("schema root must be an object");
	}
	const record = raw as Record<string, unknown>;
	const schemaVersion = record.schemaVersion;
	if (
		typeof schemaVersion !== "number" ||
		!Number.isSafeInteger(schemaVersion) ||
		schemaVersion < 1
	) {
		fail("schemaVersion must be a positive integer");
	}
	const operations = record.operations;
	if (typeof operations !== "object" || operations === null || Array.isArray(operations)) {
		fail("operations must be an object");
	}
	const operationRecord = operations as Record<string, unknown>;
	const host = parseHostOperations(operationRecord.host);
	const controller = requireStringArray(operationRecord.controller, "operations.controller");
	const nativeRoutes = parseNativeRoutes(record.nativeRoutes);
	const ownership = parseOwnership(record.ownership);
	const ownershipMethods = ownership.map((entry) => entry.method);
	if (
		ownershipMethods.length !== controller.length ||
		ownershipMethods.some((method, index) => method !== controller[index])
	) {
		fail("ownership must list the same methods in the same order as operations.controller");
	}
	const routeProblems = ownershipProblems(ownership, host, nativeRoutes);
	if (routeProblems.length > 0) fail(routeProblems.join("; "));
	const methodSchemas = parseMethodSchemas(
		record.methodSchemas,
		host.map((entry) => entry.name),
		controller,
	);
	const thinkingLevels = requireStringArray(record.thinkingLevels, "thinkingLevels");
	const promptContentBlockTypes = requireStringArray(
		record.promptContentBlockTypes,
		"promptContentBlockTypes",
	);
	const rawErrors = record.adminErrorCodes;
	if (!Array.isArray(rawErrors) || rawErrors.length === 0) {
		fail("adminErrorCodes must be a non-empty array");
	}
	const codes = new Set<number>();
	const names = new Set<string>();
	const adminErrorCodes = rawErrors.map((entry, index) => {
		if (typeof entry !== "object" || entry === null || Array.isArray(entry)) {
			fail(`adminErrorCodes[${index}] must be an object`);
		}
		const errorRecord = entry as Record<string, unknown>;
		const code = errorRecord.code;
		if (typeof code !== "number" || !Number.isSafeInteger(code) || code >= 0) {
			fail(`adminErrorCodes[${index}].code must be a negative integer`);
		}
		const name = requireString(errorRecord.name, `adminErrorCodes[${index}].name`);
		const reason = requireString(errorRecord.reason, `adminErrorCodes[${index}].reason`);
		if (codes.has(code)) fail(`adminErrorCodes contains duplicate code ${code}`);
		if (names.has(name)) fail(`adminErrorCodes contains duplicate name ${name}`);
		codes.add(code);
		names.add(name);
		return { code, name, reason };
	});
	return {
		schemaVersion,
		operations: { host, controller },
		nativeRoutes,
		ownership,
		methodSchemas,
		thinkingLevels,
		promptContentBlockTypes,
		adminErrorCodes,
	};
}

type JsNode =
	| { kind: "raw"; text: string }
	| { kind: "array"; items: readonly JsNode[] }
	| { kind: "object"; entries: readonly { key: string; value: JsNode }[] };

// Biome/Prettier-shaped printing for the generated method-schema tables so the
// committed artifact is byte-identical to generator output after `biome check`.
const METHOD_LINE_WIDTH = 100;
const METHOD_TAB_WIDTH = 2;

function flatJsNode(node: JsNode): string {
	switch (node.kind) {
		case "raw":
			return node.text;
		case "array":
			return `[${node.items.map(flatJsNode).join(", ")}]`;
		case "object":
			return `{ ${node.entries.map((entry) => `${entry.key}: ${flatJsNode(entry.value)}`).join(", ")} }`;
	}
}

// Prettier/Biome keep an array of short objects on one line, but an array of
// two or more objects that each carry multiple properties is always expanded.
function jsNodeMustBreak(node: JsNode): boolean {
	switch (node.kind) {
		case "raw":
			return false;
		case "array":
			if (
				node.items.length > 1 &&
				node.items.every((item) => item.kind === "object" && item.entries.length >= 2)
			) {
				return true;
			}
			return node.items.some(jsNodeMustBreak);
		case "object":
			return node.entries.some((entry) => jsNodeMustBreak(entry.value));
	}
}

function printJsNode(node: JsNode, indent: number, startColumn: number): string {
	const flat = flatJsNode(node);
	if (!jsNodeMustBreak(node) && startColumn + flat.length + 1 <= METHOD_LINE_WIDTH) return flat;
	if (node.kind === "raw") return flat;
	const pad = "\t".repeat(indent);
	const inner = "\t".repeat(indent + 1);
	const innerColumn = (indent + 1) * METHOD_TAB_WIDTH;
	if (node.kind === "array") {
		if (node.items.length === 0) return "[]";
		return [
			"[",
			...node.items.map((item) => `${inner}${printJsNode(item, indent + 1, innerColumn)},`),
			`${pad}]`,
		].join("\n");
	}
	return [
		"{",
		...node.entries.map(
			(entry) =>
				`${inner}${entry.key}: ${printJsNode(entry.value, indent + 1, innerColumn + entry.key.length + 2)},`,
		),
		`${pad}}`,
	].join("\n");
}

function methodFieldNode(field: MethodFieldSchema): JsNode {
	const entries: { key: string; value: JsNode }[] = [
		{ key: "name", value: { kind: "raw", text: JSON.stringify(field.name) } },
		{ key: "type", value: { kind: "raw", text: JSON.stringify(field.type) } },
	];
	if (field.optional) entries.push({ key: "optional", value: { kind: "raw", text: "true" } });
	return { kind: "object", entries };
}

function methodSchemaNode(schema: MethodSchema): JsNode {
	return {
		kind: "object",
		entries: [
			{ key: "name", value: { kind: "raw", text: JSON.stringify(schema.name) } },
			{ key: "params", value: { kind: "array", items: schema.params.map(methodFieldNode) } },
			{ key: "result", value: { kind: "array", items: schema.result.map(methodFieldNode) } },
		],
	};
}

function renderMethodSchemaRecord(name: string, schemas: readonly MethodSchema[]): string {
	const prefix = `export const ${name} = `;
	const body = printJsNode(
		{ kind: "array", items: schemas.map(methodSchemaNode) },
		0,
		prefix.length,
	);
	return `${prefix}${body} as const satisfies readonly MethodSchema[];`;
}

/** Effective status for one ownership row: host status for host routes, otherwise declared or available. */
export function ownershipStatus(
	entry: OwnershipDefinition,
	host: readonly HostOperationDefinition[],
): HostOperationStatus {
	const hostEntry = host.find((candidate) => candidate.name === entry.route);
	if (hostEntry !== undefined) return hostEntry.status;
	return entry.status ?? "available";
}

/** Effective reason for one ownership row, or undefined when the route is available. */
export function ownershipReason(
	entry: OwnershipDefinition,
	host: readonly HostOperationDefinition[],
): string | undefined {
	const hostEntry = host.find((candidate) => candidate.name === entry.route);
	if (hostEntry !== undefined) return hostEntry.reason;
	return entry.reason;
}

export function loadProtocolCatalog(schemaPath: string): ProtocolCatalog {
	let text: string;
	try {
		text = readFileSync(schemaPath, "utf8");
	} catch (error) {
		fail(`cannot read ${schemaPath}: ${(error as Error).message}`);
	}
	try {
		return parseProtocolCatalog(JSON.parse(text));
	} catch (error) {
		if (error instanceof SyntaxError) fail(`invalid JSON in ${schemaPath}: ${error.message}`);
		throw error;
	}
}

function stringLiteralList(values: readonly string[], indent = "\t"): string {
	return values.map((value) => `${indent}${JSON.stringify(value)},`).join("\n");
}

/** Matches Biome's formatting: collapse to one line when it fits within the 100-column budget. */
function renderExportedStringArray(name: string, values: readonly string[]): string {
	const inline = `export const ${name} = [${values.map((value) => JSON.stringify(value)).join(", ")}] as const;`;
	if (inline.length <= 100) return inline;
	return [`export const ${name} = [`, stringLiteralList(values), "] as const;"].join("\n");
}

function goStringBoolMap(values: readonly string[], indent = "\t"): string {
	const keys = values.map((value) => JSON.stringify(value));
	const width = Math.max(...keys.map((key) => key.length));
	return keys.map((key) => `${indent}${key}:${" ".repeat(width - key.length + 1)}true,`).join("\n");
}

/** Match Biome's 100-column wrapping: break the value onto its own indented line. */
function renderRecordEntry(key: string, value: string, indent = "\t"): string {
	const inline = `${indent}${JSON.stringify(key)}: ${JSON.stringify(value)},`;
	if (inline.length < 100) return inline;
	return `${indent}${JSON.stringify(key)}:\n${indent}\t${JSON.stringify(value)},`;
}

function renderStatusRecord(host: readonly HostOperationDefinition[]): string {
	const lines = host.map((entry) => renderRecordEntry(entry.name, entry.status));
	return [
		"export const HOST_OPERATION_STATUS: Record<HostOperation, HostOperationStatus> = {",
		...lines,
		"};",
	].join("\n");
}

function renderReasonRecord(host: readonly HostOperationDefinition[]): string {
	const entries = host.filter((entry) => entry.reason !== undefined);
	if (entries.length === 0)
		return "export const HOST_OPERATION_REASONS: Partial<Record<HostOperation, string>> = {};";
	return [
		"export const HOST_OPERATION_REASONS: Partial<Record<HostOperation, string>> = {",
		...entries.map((entry) => renderRecordEntry(entry.name, entry.reason as string)),
		"};",
	].join("\n");
}

function renderMethodStringRecord(
	declaration: string,
	methods: readonly string[],
	values: readonly string[],
): string {
	return [
		declaration,
		...methods.map((method, index) => renderRecordEntry(method, values[index] ?? "")),
		"};",
	].join("\n");
}

function renderMethodReasonRecord(catalog: ProtocolCatalog): string {
	const lines = catalog.ownership
		.map((entry) => ({
			method: entry.method,
			reason: ownershipReason(entry, catalog.operations.host),
		}))
		.filter((entry) => entry.reason !== undefined)
		.map((entry) => renderRecordEntry(entry.method, entry.reason as string));
	return [
		"export const CONTROLLER_METHOD_REASONS: Partial<Record<ControllerMethod, string>> = {",
		...lines,
		"};",
	].join("\n");
}

export function renderTypeScript(catalog: ProtocolCatalog): string {
	const { host, controller } = catalog.operations;
	const available = host.filter((entry) => entry.status === "available").map((entry) => entry.name);
	const ownership = catalog.ownership;
	return [
		`// ${GENERATED_HEADER}`,
		"",
		`export const PROTOCOL_CATALOG_SCHEMA_VERSION = ${catalog.schemaVersion};`,
		"",
		renderExportedStringArray(
			"HOST_OPERATIONS",
			host.map((entry) => entry.name),
		),
		"",
		"export type HostOperation = (typeof HOST_OPERATIONS)[number];",
		"",
		renderExportedStringArray("HOST_OPERATION_STATUSES", [...HOST_OPERATION_STATUSES]),
		"",
		"export type HostOperationStatus = (typeof HOST_OPERATION_STATUSES)[number];",
		"",
		renderStatusRecord(host),
		"",
		renderExportedStringArray("HOST_AVAILABLE_OPERATIONS", available),
		"",
		"export type HostAvailableOperation = (typeof HOST_AVAILABLE_OPERATIONS)[number];",
		"",
		renderReasonRecord(host),
		"",
		renderExportedStringArray("CONTROLLER_METHODS", controller),
		"",
		"export type ControllerMethod = (typeof CONTROLLER_METHODS)[number];",
		"",
		renderExportedStringArray("NATIVE_CONTROLLER_ROUTES", catalog.nativeRoutes.controller),
		"",
		"export type NativeControllerRoute = (typeof NATIVE_CONTROLLER_ROUTES)[number];",
		"",
		renderExportedStringArray("NATIVE_WORKSPACE_ROUTES", catalog.nativeRoutes.workspace),
		"",
		"export type NativeWorkspaceRoute = (typeof NATIVE_WORKSPACE_ROUTES)[number];",
		"",
		renderMethodStringRecord(
			"export const CONTROLLER_METHOD_OWNERS: Record<ControllerMethod, string> = {",
			controller,
			ownership.map((entry) => entry.owner),
		),
		"",
		renderMethodStringRecord(
			"export const CONTROLLER_METHOD_ROUTES: Record<ControllerMethod, string> = {",
			controller,
			ownership.map((entry) => entry.route),
		),
		"",
		renderMethodStringRecord(
			"export const CONTROLLER_METHOD_FC: Record<ControllerMethod, string> = {",
			controller,
			ownership.map((entry) => entry.fc),
		),
		"",
		renderMethodStringRecord(
			"export const CONTROLLER_METHOD_PROFILES: Record<ControllerMethod, string> = {",
			controller,
			ownership.map((entry) => entry.profile),
		),
		"",
		renderMethodStringRecord(
			"export const CONTROLLER_METHOD_STATUS: Record<ControllerMethod, HostOperationStatus> = {",
			controller,
			ownership.map((entry) => ownershipStatus(entry, host)),
		),
		"",
		renderMethodReasonRecord(catalog),
		"",
		renderExportedStringArray("METHOD_FIELD_TYPES", [...METHOD_FIELD_TYPES]),
		"",
		"export type MethodFieldType = (typeof METHOD_FIELD_TYPES)[number];",
		"",
		"export interface MethodFieldSchema {",
		"\tname: string;",
		"\ttype: MethodFieldType;",
		"\toptional?: boolean;",
		"}",
		"",
		"export interface MethodSchema {",
		"\tname: string;",
		"\tparams: MethodFieldSchema[];",
		"\tresult: MethodFieldSchema[];",
		"}",
		"",
		renderMethodSchemaRecord("HOST_METHOD_SCHEMAS", catalog.methodSchemas.host),
		"",
		renderMethodSchemaRecord("CONTROLLER_METHOD_SCHEMAS", catalog.methodSchemas.controller),
		"",
		renderExportedStringArray("THINKING_LEVELS", catalog.thinkingLevels),
		"",
		"export type CatalogThinkingLevel = (typeof THINKING_LEVELS)[number];",
		"",
		renderExportedStringArray("PROMPT_CONTENT_BLOCK_TYPES", catalog.promptContentBlockTypes),
		"",
		"export type PromptContentBlockType = (typeof PROMPT_CONTENT_BLOCK_TYPES)[number];",
		"",
		"export const ADMIN_ERROR_CODES = [",
		...catalog.adminErrorCodes.map(
			(entry) =>
				`\t{ code: ${entry.code}, name: ${JSON.stringify(entry.name)}, reason: ${JSON.stringify(entry.reason)} },`,
		),
		"] as const;",
		"",
		'export type AdminErrorCode = (typeof ADMIN_ERROR_CODES)[number]["code"];',
		"",
	].join("\n");
}

function goStringMap(
	entries: readonly { readonly key: string; readonly value: string }[],
	indent = "\t",
): string {
	if (entries.length === 0) return "";
	const keys = entries.map((entry) => JSON.stringify(entry.key));
	const width = Math.max(...keys.map((key) => key.length));
	return entries
		.map((entry, index) => {
			const key = keys[index] ?? "";
			return `${indent}${key}:${" ".repeat(width - key.length + 1)}${JSON.stringify(entry.value)},`;
		})
		.join("\n");
}

function renderGoMethodField(field: MethodFieldSchema): string {
	if (field.optional) {
		return `{Name: ${JSON.stringify(field.name)}, Type: ${JSON.stringify(field.type)}, Optional: true}`;
	}
	return `{Name: ${JSON.stringify(field.name)}, Type: ${JSON.stringify(field.type)}}`;
}

function renderGoMethodSchemaRecord(name: string, schemas: readonly MethodSchema[]): string {
	const lines = schemas.map(
		(schema) =>
			`\t{Name: ${JSON.stringify(schema.name)}, Params: []CatalogMethodField{${schema.params
				.map(renderGoMethodField)
				.join(", ")}}, Result: []CatalogMethodField{${schema.result
				.map(renderGoMethodField)
				.join(", ")}}},`,
	);
	return [`var ${name} = []CatalogMethodSchema{`, ...lines, "}"].join("\n");
}

export function renderGo(catalog: ProtocolCatalog): string {
	const { host, controller } = catalog.operations;
	const names = host.map((entry) => entry.name);
	const available = host.filter((entry) => entry.status === "available").map((entry) => entry.name);
	const reasons = host
		.filter((entry) => entry.reason !== undefined)
		.map((entry) => ({ key: entry.name, value: entry.reason as string }));
	return [
		`// ${GENERATED_HEADER}`,
		"",
		"package piprotocol",
		"",
		"import (",
		'\t"encoding/json"',
		'\t"fmt"',
		'\t"strings"',
		")",
		"",
		"// CatalogSchemaVersion is the protocol catalog schema revision.",
		`const CatalogSchemaVersion = ${catalog.schemaVersion}`,
		"",
		"// Host operation implementation statuses. Only CatalogHostOperationAvailable",
		"// routes may be negotiated by a host; the other statuses stay catalogued so",
		"// callers can fail closed with a stated reason.",
		"const (",
		'\tCatalogHostOperationAvailable   = "available"',
		'\tCatalogHostOperationUnavailable = "unavailable"',
		'\tCatalogHostOperationAbsent      = "absent"',
		")",
		"",
		"// CatalogHostOperations lists every catalogued host operation key.",
		"var CatalogHostOperations = []string{",
		stringLiteralList(names),
		"}",
		"",
		"// CatalogHostOperationSet indexes CatalogHostOperations for exact membership lookup.",
		"var CatalogHostOperationSet = map[string]bool{",
		goStringBoolMap(names),
		"}",
		"",
		"// CatalogHostOperationStatus records the explicit implementation status per operation.",
		"var CatalogHostOperationStatus = map[string]string{",
		goStringMap(host.map((entry) => ({ key: entry.name, value: entry.status }))),
		"}",
		"",
		"// CatalogHostAvailableOperations lists the operations a host may advertise.",
		"var CatalogHostAvailableOperations = []string{",
		stringLiteralList(available),
		"}",
		"",
		"// CatalogHostAvailableOperationSet indexes CatalogHostAvailableOperations.",
		"var CatalogHostAvailableOperationSet = map[string]bool{",
		goStringBoolMap(available),
		"}",
		"",
		"// CatalogHostOperationReasons records why a non-available operation stays unavailable.",
		"var CatalogHostOperationReasons = map[string]string{",
		goStringMap(reasons),
		"}",
		"",
		"// CatalogHostOperationIsAvailable reports whether the catalog marks an operation available.",
		"func CatalogHostOperationIsAvailable(name string) bool {",
		"\treturn CatalogHostAvailableOperationSet[name]",
		"}",
		"",
		"// CatalogControllerMethods lists the browser/controller method names from ws-protocol.ts.",
		"var CatalogControllerMethods = []string{",
		stringLiteralList(controller),
		"}",
		"",
		"// CatalogControllerMethodSet indexes CatalogControllerMethods for exact membership lookup.",
		"var CatalogControllerMethodSet = map[string]bool{",
		goStringBoolMap(controller),
		"}",
		"",
		"// CatalogNativeControllerRoutes lists the controller-owned native route namespaces.",
		"var CatalogNativeControllerRoutes = []string{",
		stringLiteralList(catalog.nativeRoutes.controller),
		"}",
		"",
		"// CatalogNativeWorkspaceRoutes lists the workspace-owned native route namespaces.",
		"var CatalogNativeWorkspaceRoutes = []string{",
		stringLiteralList(catalog.nativeRoutes.workspace),
		"}",
		"",
		"// CatalogNativeControllerRouteSet indexes CatalogNativeControllerRoutes.",
		"var CatalogNativeControllerRouteSet = map[string]bool{",
		goStringBoolMap(catalog.nativeRoutes.controller),
		"}",
		"",
		"// CatalogNativeWorkspaceRouteSet indexes CatalogNativeWorkspaceRoutes.",
		"var CatalogNativeWorkspaceRouteSet = map[string]bool{",
		goStringBoolMap(catalog.nativeRoutes.workspace),
		"}",
		"",
		"// CatalogNativeRouteKnown reports whether a browser method route is a host",
		"// operation or a declared controller/workspace route. An unknown route must",
		"// fail closed instead of being treated as locally owned.",
		"func CatalogNativeRouteKnown(route string) bool {",
		"\tif CatalogHostOperationSet[route] {",
		"\t\treturn true",
		"\t}",
		'\tif namespace, id, found := strings.Cut(route, ":"); found {',
		"\t\tswitch namespace {",
		'\t\tcase "controller":',
		"\t\t\treturn CatalogNativeControllerRouteSet[id]",
		'\t\tcase "workspace":',
		"\t\t\treturn CatalogNativeWorkspaceRouteSet[id]",
		"\t\t}",
		"\t}",
		"\treturn false",
		"}",
		"",
		"// CatalogControllerMethodOwners records the declared owner per browser method.",
		"var CatalogControllerMethodOwners = map[string]string{",
		goStringMap(catalog.ownership.map((entry) => ({ key: entry.method, value: entry.owner }))),
		"}",
		"",
		"// CatalogControllerMethodRoutes records the native route per browser method.",
		"var CatalogControllerMethodRoutes = map[string]string{",
		goStringMap(catalog.ownership.map((entry) => ({ key: entry.method, value: entry.route }))),
		"}",
		"",
		"// CatalogControllerMethodFC records the frozen FC feature-coverage label per browser method.",
		"var CatalogControllerMethodFC = map[string]string{",
		goStringMap(catalog.ownership.map((entry) => ({ key: entry.method, value: entry.fc }))),
		"}",
		"",
		"// CatalogControllerMethodProfiles records the agent profile per browser method.",
		"var CatalogControllerMethodProfiles = map[string]string{",
		goStringMap(catalog.ownership.map((entry) => ({ key: entry.method, value: entry.profile }))),
		"}",
		"",
		"// CatalogControllerMethodStatus records the effective status per browser method. A",
		"// host route carries the generated host status; a controller/workspace route is",
		"// available unless it declares an explicit fail-closed status.",
		"var CatalogControllerMethodStatus = map[string]string{",
		goStringMap(
			catalog.ownership.map((entry) => ({
				key: entry.method,
				value: ownershipStatus(entry, host),
			})),
		),
		"}",
		"",
		"// CatalogControllerMethodReasons records why a non-available browser method fails closed.",
		"var CatalogControllerMethodReasons = map[string]string{",
		goStringMap(
			catalog.ownership
				.map((entry) => ({
					key: entry.method,
					value: ownershipReason(entry, host),
				}))
				.filter((entry): entry is { key: string; value: string } => entry.value !== undefined),
		),
		"}",
		"",
		"// CatalogControllerMethodIsAvailable reports whether a browser method is dispatchable.",
		"func CatalogControllerMethodIsAvailable(method string) bool {",
		"\treturn CatalogControllerMethodStatus[method] == CatalogHostOperationAvailable",
		"}",
		"",
		"// CatalogMethodField is one required or optional field of a method schema.",
		"type CatalogMethodField struct {",
		"\tName     string",
		"\tType     string",
		"\tOptional bool",
		"}",
		"",
		"// CatalogMethodSchema is the generated parameter/result schema for one method. A",
		"// method with no schema is envelope-validated only; unknown fields stay additive.",
		"type CatalogMethodSchema struct {",
		"\tName   string",
		"\tParams []CatalogMethodField",
		"\tResult []CatalogMethodField",
		"}",
		"",
		renderGoMethodSchemaRecord("CatalogHostMethodSchemas", catalog.methodSchemas.host),
		"",
		renderGoMethodSchemaRecord("CatalogControllerMethodSchemas", catalog.methodSchemas.controller),
		"",
		"func catalogFieldTypeMatches(typeName string, raw json.RawMessage) bool {",
		"\ttrimmed := strings.TrimSpace(string(raw))",
		'\tif trimmed == "" {',
		"\t\treturn false",
		"\t}",
		"\tswitch typeName {",
		'\tcase "string":',
		"\t\treturn trimmed[0] == '\"'",
		'\tcase "boolean":',
		'\t\treturn trimmed == "true" || trimmed == "false"',
		'\tcase "number":',
		"\t\tvar value float64",
		"\t\treturn json.Unmarshal(raw, &value) == nil",
		'\tcase "object":',
		"\t\tvar value map[string]json.RawMessage",
		"\t\treturn json.Unmarshal(raw, &value) == nil",
		'\tcase "array":',
		"\t\tvar value []json.RawMessage",
		"\t\treturn json.Unmarshal(raw, &value) == nil",
		"\tdefault:",
		"\t\treturn false",
		"\t}",
		"}",
		"",
		"func catalogValidateMethodFields(kind, method string, fields []CatalogMethodField, raw json.RawMessage) error {",
		"\tif len(fields) == 0 {",
		"\t\treturn nil",
		"\t}",
		"\ttrimmed := strings.TrimSpace(string(raw))",
		'\tif trimmed == "" || trimmed == "null" {',
		'\t\treturn fmt.Errorf("%s %s payload is missing", kind, method)',
		"\t}",
		"\tvar object map[string]json.RawMessage",
		"\tif err := json.Unmarshal(raw, &object); err != nil {",
		'\t\treturn fmt.Errorf("%s %s payload must be an object", kind, method)',
		"\t}",
		"\tfor _, field := range fields {",
		"\t\tvalue, present := object[field.Name]",
		'\t\tif !present || strings.TrimSpace(string(value)) == "null" {',
		"\t\t\tif field.Optional {",
		"\t\t\t\tcontinue",
		"\t\t\t}",
		'\t\t\treturn fmt.Errorf("%s %s payload is missing %q", kind, method, field.Name)',
		"\t\t}",
		"\t\tif !catalogFieldTypeMatches(field.Type, value) {",
		'\t\t\treturn fmt.Errorf("%s %s payload field %q must be %s", kind, method, field.Name, field.Type)',
		"\t\t}",
		"\t}",
		"\treturn nil",
		"}",
		"",
		"func catalogValidateMethod(schemas []CatalogMethodSchema, kind, method string, raw json.RawMessage, result bool) error {",
		"\tfor _, schema := range schemas {",
		"\t\tif schema.Name != method {",
		"\t\t\tcontinue",
		"\t\t}",
		"\t\tif result {",
		"\t\t\treturn catalogValidateMethodFields(kind, method, schema.Result, raw)",
		"\t\t}",
		"\t\treturn catalogValidateMethodFields(kind, method, schema.Params, raw)",
		"\t}",
		"\treturn nil",
		"}",
		"",
		"// ValidateHostMethodParams rejects a malformed host request before dispatch.",
		"func ValidateHostMethodParams(method string, raw json.RawMessage) error {",
		'\treturn catalogValidateMethod(CatalogHostMethodSchemas, "host request", method, raw, false)',
		"}",
		"",
		"// ValidateHostMethodResult rejects an invalid host result before projection.",
		"func ValidateHostMethodResult(method string, raw json.RawMessage) error {",
		'\treturn catalogValidateMethod(CatalogHostMethodSchemas, "host result", method, raw, true)',
		"}",
		"",
		"// ValidateControllerMethodParams rejects a malformed browser request before dispatch.",
		"func ValidateControllerMethodParams(method string, raw json.RawMessage) error {",
		'\treturn catalogValidateMethod(CatalogControllerMethodSchemas, "controller request", method, raw, false)',
		"}",
		"",
		"// ValidateControllerMethodResult rejects an invalid browser result before projection.",
		"func ValidateControllerMethodResult(method string, raw json.RawMessage) error {",
		'\treturn catalogValidateMethod(CatalogControllerMethodSchemas, "controller result", method, raw, true)',
		"}",
		"",
		"// ValidateHostErrorEnvelope requires the versioned host error shape.",
		"func ValidateHostErrorEnvelope(raw json.RawMessage) error {",
		"\tvar envelope struct {",
		'\t\tCode    *int    `json:"code"`',
		'\t\tMessage *string `json:"message"`',
		"\t}",
		"\tif err := json.Unmarshal(raw, &envelope); err != nil {",
		'\t\treturn fmt.Errorf("host error envelope must be an object: %w", err)',
		"\t}",
		"\tif envelope.Code == nil || envelope.Message == nil {",
		'\t\treturn fmt.Errorf("host error envelope requires code and message")',
		"\t}",
		"\treturn nil",
		"}",
		"",
		"// CatalogThinkingLevels lists the accepted thinking levels.",
		"var CatalogThinkingLevels = []string{",
		stringLiteralList(catalog.thinkingLevels),
		"}",
		"",
		"// CatalogPromptContentBlockTypes lists the accepted prompt content block types.",
		"var CatalogPromptContentBlockTypes = []string{",
		stringLiteralList(catalog.promptContentBlockTypes),
		"}",
		"",
		"// CatalogAdminError is a versioned admin error code.",
		"type CatalogAdminError struct {",
		"\tCode   int",
		"\tName   string",
		"\tReason string",
		"}",
		"",
		"// CatalogAdminErrorCodes lists the versioned admin error codes used by the host.",
		"var CatalogAdminErrorCodes = []CatalogAdminError{",
		...catalog.adminErrorCodes.map(
			(entry) =>
				`\t{Code: ${entry.code}, Name: ${JSON.stringify(entry.name)}, Reason: ${JSON.stringify(entry.reason)}},`,
		),
		"}",
		"",
	].join("\n");
}

export function buildArtifacts(catalog: ProtocolCatalog): GeneratedArtifact[] {
	return [
		{ path: TYPESCRIPT_ARTIFACT_PATH, content: renderTypeScript(catalog) },
		{ path: GO_ARTIFACT_PATH, content: renderGo(catalog) },
	];
}

export function writeArtifacts(baseDir: string, artifacts: readonly GeneratedArtifact[]): void {
	for (const artifact of artifacts) {
		const target = resolve(baseDir, artifact.path);
		mkdirSync(dirname(target), { recursive: true });
		writeFileSync(target, artifact.content);
	}
}

/** Directory that contains shared/package.json. */
export function defaultPackageDir(): string {
	return resolve(import.meta.dir, "..", "..", "shared");
}

export function generateContracts(packageDir = defaultPackageDir()): GeneratedArtifact[] {
	const catalog = loadProtocolCatalog(resolve(packageDir, SCHEMA_RELATIVE_PATH));
	return buildArtifacts(catalog);
}

if (import.meta.main) {
	const packageDir = defaultPackageDir();
	const artifacts = generateContracts(packageDir);
	writeArtifacts(packageDir, artifacts);
	for (const artifact of artifacts) console.log(`generate-contracts: wrote ${artifact.path}`);
}
