import { expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { compareArtifacts, runContractCheck } from "../../../web/scripts/check-contracts";
import {
	GO_ARTIFACT_PATH,
	generateContracts,
	loadProtocolCatalog,
	renderGo,
	renderTypeScript,
	SCHEMA_RELATIVE_PATH,
	TYPESCRIPT_ARTIFACT_PATH,
	writeArtifacts,
} from "../../../web/scripts/generate-contracts";
import {
	ADMIN_ERROR_CODES,
	CONTROLLER_METHOD_FC,
	CONTROLLER_METHOD_OWNERS,
	CONTROLLER_METHOD_PROFILES,
	CONTROLLER_METHOD_REASONS,
	CONTROLLER_METHOD_ROUTES,
	CONTROLLER_METHOD_STATUS,
	CONTROLLER_METHODS,
	HOST_AVAILABLE_OPERATIONS,
	HOST_OPERATION_REASONS,
	HOST_OPERATION_STATUS,
	HOST_OPERATION_STATUSES,
	HOST_OPERATIONS,
	NATIVE_CONTROLLER_ROUTES,
	NATIVE_WORKSPACE_ROUTES,
	PROMPT_CONTENT_BLOCK_TYPES,
	THINKING_LEVELS,
} from "../../src/generated/protocol-catalog";

const base = import.meta.dir;
const packageDir = resolve(base, "..", "..");
const schema = loadProtocolCatalog(join(packageDir, SCHEMA_RELATIVE_PATH));

test("generated TypeScript catalog matches the schema", () => {
	expect(schema.schemaVersion).toBe(2);
	expect(schema.operations.host.map((entry) => entry.name)).toEqual([...HOST_OPERATIONS]);
	expect(schema.operations.controller).toEqual([...CONTROLLER_METHODS]);
	expect(schema.nativeRoutes.controller).toEqual([...NATIVE_CONTROLLER_ROUTES]);
	expect(schema.nativeRoutes.workspace).toEqual([...NATIVE_WORKSPACE_ROUTES]);
	expect(schema.thinkingLevels).toEqual([...THINKING_LEVELS]);
	expect(schema.promptContentBlockTypes).toEqual([...PROMPT_CONTENT_BLOCK_TYPES]);
	expect(schema.adminErrorCodes).toEqual(ADMIN_ERROR_CODES.map((entry) => ({ ...entry })));
});

test("generated ownership records match the schema ownership table", () => {
	const byMethod = new Map(schema.ownership.map((entry) => [entry.method, entry]));
	for (const method of CONTROLLER_METHODS) {
		const entry = byMethod.get(method);
		expect(entry).toBeDefined();
		if (!entry) continue;
		expect(CONTROLLER_METHOD_OWNERS[method]).toBe(entry.owner);
		expect(CONTROLLER_METHOD_ROUTES[method]).toBe(entry.route);
		expect(CONTROLLER_METHOD_FC[method]).toBe(entry.fc);
		expect(CONTROLLER_METHOD_PROFILES[method]).toBe(entry.profile);
		const hostStatus = HOST_OPERATION_STATUS[entry.route as keyof typeof HOST_OPERATION_STATUS];
		const reason = CONTROLLER_METHOD_REASONS[method];
		if (hostStatus !== undefined) {
			expect(CONTROLLER_METHOD_STATUS[method]).toBe(hostStatus);
			if (hostStatus === "available") expect(reason).toBeUndefined();
			else expect(reason).toBe(HOST_OPERATION_REASONS[entry.route as never]);
		} else {
			expect(CONTROLLER_METHOD_STATUS[method]).toBe(entry.status ?? "available");
			if (entry.status === "unavailable") expect(reason).toBe(entry.reason);
		}
	}
	// The ownership table cannot drop or add a browser method.
	expect(schema.ownership.map((entry) => entry.method)).toEqual([...CONTROLLER_METHODS]);
});

test("every host operation carries an explicit implementation status", () => {
	const statusByName = HOST_OPERATION_STATUS as Record<string, string>;
	const reasonByName = HOST_OPERATION_REASONS as Record<string, string | undefined>;
	const availableNames: readonly string[] = HOST_AVAILABLE_OPERATIONS;
	expect(schema.operations.host.length).toBeGreaterThan(0);
	expect(new Set(HOST_OPERATIONS).size).toBe(HOST_OPERATIONS.length);
	expect(new Set(HOST_OPERATION_STATUSES)).toEqual(new Set(["available", "unavailable", "absent"]));
	for (const entry of schema.operations.host) {
		expect(statusByName[entry.name]).toBe(entry.status);
		if (entry.status === "available") {
			expect(availableNames).toContain(entry.name);
			expect(entry.reason).toBeUndefined();
			continue;
		}
		expect(availableNames).not.toContain(entry.name);
		expect(typeof entry.reason).toBe("string");
		expect((entry.reason ?? "").length).toBeGreaterThan(0);
		expect(reasonByName[entry.name]).toBe(entry.reason);
	}
	// A negotiated host can only advertise the available subset, and that subset
	// is exactly what the schema marks available.
	expect([...availableNames]).toEqual(
		schema.operations.host
			.filter((entry) => entry.status === "available")
			.map((entry) => entry.name),
	);
});

test("committed generated TypeScript and Go files are the schema renderings", () => {
	const typescript = readFileSync(join(packageDir, TYPESCRIPT_ARTIFACT_PATH), "utf8");
	const go = readFileSync(join(packageDir, GO_ARTIFACT_PATH), "utf8");
	expect(typescript).toBe(renderTypeScript(schema));
	expect(go).toBe(renderGo(schema));
	expect(go).toContain("// Code generated by generate-contracts.ts; DO NOT EDIT.");
	expect(typescript).toContain("// Code generated by generate-contracts.ts; DO NOT EDIT.");
	expect(go).toContain("package piprotocol");
});

test("Bun host operation set derives from the shared catalog", () => {
	const source = readFileSync(join(packageDir, "..", "assistant", "src", "host.ts"), "utf8");
	expect(source).toContain("../../shared/src/generated/protocol-catalog");
	expect(source).toContain("HOST_AVAILABLE_OPERATIONS");
	expect(source).toContain("HOST_OPERATIONS.map");
	// The host must not reintroduce a hand-maintained implemented-operation
	// allowlist that can drift from the catalog statuses. Policy sets over method
	// names (for example the AUX-13 lease's mutating-method set) are allowed.
	expect(source).not.toContain("IMPLEMENTED_OPERATIONS");
	expect(source).toContain("new Set<string>(HOST_AVAILABLE_OPERATIONS)");
	expect(HOST_AVAILABLE_OPERATIONS.length).toBeGreaterThan(0);
	expect(HOST_AVAILABLE_OPERATIONS.length).toBeLessThan(HOST_OPERATIONS.length);
	expect(new Set(HOST_AVAILABLE_OPERATIONS).size).toBe(HOST_AVAILABLE_OPERATIONS.length);
});

test("thinking levels and prompt content block types match the schema", () => {
	expect([...THINKING_LEVELS]).toEqual(["off", "minimal", "low", "medium", "high", "xhigh", "max"]);
	expect([...PROMPT_CONTENT_BLOCK_TYPES]).toEqual(["text", "image", "resource"]);
	expect(schema.thinkingLevels).toEqual([...THINKING_LEVELS]);
	expect(schema.promptContentBlockTypes).toEqual([...PROMPT_CONTENT_BLOCK_TYPES]);
	expect(new Set(THINKING_LEVELS).size).toBe(THINKING_LEVELS.length);
	expect(new Set(PROMPT_CONTENT_BLOCK_TYPES).size).toBe(PROMPT_CONTENT_BLOCK_TYPES.length);
});

test("check-contracts detects drift in a mutated temporary copy", () => {
	const artifacts = generateContracts(packageDir);
	expect(compareArtifacts(artifacts, packageDir)).toEqual([]);
	expect(runContractCheck({ packageDir })).toBe(0);

	const staging = mkdtempSync(join(tmpdir(), "pixie-contracts-test-"));
	try {
		writeArtifacts(staging, artifacts);
		expect(compareArtifacts(artifacts, staging)).toEqual([]);
		const target = join(staging, GO_ARTIFACT_PATH);
		writeFileSync(target, `${readFileSync(target, "utf8")}// mutated by test\n`);
		const drift = compareArtifacts(artifacts, staging);
		expect(drift.length).toBe(1);
		expect(drift[0]?.path).toBe(GO_ARTIFACT_PATH);
		expect(drift[0]?.reason).toBe("content");
		expect(drift[0]?.diff).toContain("// mutated by test");
		expect(runContractCheck({ packageDir, committedDir: staging })).toBe(1);
	} finally {
		rmSync(staging, { recursive: true, force: true });
	}
});

test("check-contracts reports a missing committed artifact", () => {
	const artifacts = generateContracts(packageDir);
	const staging = mkdtempSync(join(tmpdir(), "pixie-contracts-missing-"));
	try {
		writeArtifacts(
			staging,
			artifacts.filter((artifact) => artifact.path !== GO_ARTIFACT_PATH),
		);
		const drift = compareArtifacts(artifacts, staging);
		expect(drift.length).toBe(1);
		expect(drift[0]?.path).toBe(GO_ARTIFACT_PATH);
		expect(drift[0]?.reason).toBe("missing");
	} finally {
		rmSync(staging, { recursive: true, force: true });
	}
});
