import { expect, test } from "bun:test";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { compareArtifacts, runContractCheck } from "../../../web/scripts/check-contracts";
import {
	GO_ARTIFACT_PATH,
	generateContracts,
	loadProtocolCatalog,
	renderGo,
	renderTypeScript,
	SCHEMA_RELATIVE_PATH,
	TYPESCRIPT_ARTIFACT_PATH,
	writeArtifacts,
} from "../../../web/scripts/generate-contracts";
import {
	ADMIN_ERROR_CODES,
	CONTROLLER_METHODS,
	HOST_OPERATIONS,
	PROMPT_CONTENT_BLOCK_TYPES,
	THINKING_LEVELS,
} from "../../src/generated/protocol-catalog";

const base = import.meta.dir;
const packageDir = resolve(base, "..", "..");
const schema = loadProtocolCatalog(join(packageDir, SCHEMA_RELATIVE_PATH));

/**
 * Reads the Bun host's implemented-operation allowlist from its TypeScript
 * source. The shared schema stays the single source of truth: the Bun host
 * derives its advertised operationSet from the generated HOST_OPERATIONS
 * catalog, so drift here is a real failure.
 */
function extractBunImplementedOperations(source: string): string[] {
	const block = source.match(/const IMPLEMENTED_OPERATIONS = new Set\(\[([\s\S]*?)\]\)/);
	if (block === null) throw new Error("IMPLEMENTED_OPERATIONS literal not found");
	return [...(block[1] ?? "").matchAll(/"([^"]+)"/g)].map((match) => match[1] ?? "");
}

test("generated TypeScript catalog matches the schema", () => {
	expect(schema.schemaVersion).toBe(1);
	expect(schema.operations.host).toEqual([...HOST_OPERATIONS]);
	expect(schema.operations.controller).toEqual([...CONTROLLER_METHODS]);
	expect(schema.thinkingLevels).toEqual([...THINKING_LEVELS]);
	expect(schema.promptContentBlockTypes).toEqual([...PROMPT_CONTENT_BLOCK_TYPES]);
	expect(schema.adminErrorCodes).toEqual(ADMIN_ERROR_CODES.map((entry) => ({ ...entry })));
});

test("committed generated TypeScript and Go files are the schema renderings", () => {
	const typescript = readFileSync(join(packageDir, TYPESCRIPT_ARTIFACT_PATH), "utf8");
	const go = readFileSync(join(packageDir, GO_ARTIFACT_PATH), "utf8");
	expect(typescript).toBe(renderTypeScript(schema));
	expect(go).toBe(renderGo(schema));
	expect(go).toContain("// Code generated by generate-contracts.ts; DO NOT EDIT.");
	expect(typescript).toContain("// Code generated by generate-contracts.ts; DO NOT EDIT.");
	expect(go).toContain("package piprotocol");
});

test("Bun host operation set derives from the shared catalog", () => {
	const source = readFileSync(join(packageDir, "..", "assistant", "src", "host.ts"), "utf8");
	expect(source).toContain("../../shared/src/generated/protocol-catalog");
	expect(source).toContain("HOST_OPERATIONS.map");
	const implemented = extractBunImplementedOperations(source);
	expect(implemented.length).toBeGreaterThan(0);
	expect(new Set(implemented).size).toBe(implemented.length);
	expect(schema.operations.host).toEqual([...HOST_OPERATIONS]);
});

test("thinking levels and prompt content block types match the schema", () => {
	expect([...THINKING_LEVELS]).toEqual(["off", "minimal", "low", "medium", "high", "xhigh", "max"]);
	expect([...PROMPT_CONTENT_BLOCK_TYPES]).toEqual(["text", "image", "resource"]);
	expect(schema.thinkingLevels).toEqual([...THINKING_LEVELS]);
	expect(schema.promptContentBlockTypes).toEqual([...PROMPT_CONTENT_BLOCK_TYPES]);
	expect(new Set(THINKING_LEVELS).size).toBe(THINKING_LEVELS.length);
	expect(new Set(PROMPT_CONTENT_BLOCK_TYPES).size).toBe(PROMPT_CONTENT_BLOCK_TYPES.length);
});

test("check-contracts detects drift in a mutated temporary copy", () => {
	const artifacts = generateContracts(packageDir);
	expect(compareArtifacts(artifacts, packageDir)).toEqual([]);
	expect(runContractCheck({ packageDir })).toBe(0);

	const staging = mkdtempSync(join(tmpdir(), "pixie-contracts-test-"));
	try {
		writeArtifacts(staging, artifacts);
		expect(compareArtifacts(artifacts, staging)).toEqual([]);
		const target = join(staging, GO_ARTIFACT_PATH);
		writeFileSync(target, `${readFileSync(target, "utf8")}// mutated by test\n`);
		const drift = compareArtifacts(artifacts, staging);
		expect(drift.length).toBe(1);
		expect(drift[0]?.path).toBe(GO_ARTIFACT_PATH);
		expect(drift[0]?.reason).toBe("content");
		expect(drift[0]?.diff).toContain("// mutated by test");
		expect(runContractCheck({ packageDir, committedDir: staging })).toBe(1);
	} finally {
		rmSync(staging, { recursive: true, force: true });
	}
});

test("check-contracts reports a missing committed artifact", () => {
	const artifacts = generateContracts(packageDir);
	const staging = mkdtempSync(join(tmpdir(), "pixie-contracts-missing-"));
	try {
		writeArtifacts(
			staging,
			artifacts.filter((artifact) => artifact.path !== GO_ARTIFACT_PATH),
		);
		const drift = compareArtifacts(artifacts, staging);
		expect(drift.length).toBe(1);
		expect(drift[0]?.path).toBe(GO_ARTIFACT_PATH);
		expect(drift[0]?.reason).toBe("missing");
	} finally {
		rmSync(staging, { recursive: true, force: true });
	}
});
