#!/usr/bin/env bun

/**
 * AUX-10 — Configuration JSON Schema generator and stale-check.
 *
 * Emits `docs/config-schema.json`, a documentation and drift-detection schema
 * for the two private JSON configuration surfaces:
 *
 *   - controller: `runtimeConfigFile` in `cmd/pixie-web/config.go`
 *   - assistant:  `ASSISTANT_CONFIG_FIELDS` in `src/assistant/serve.ts`,
 *     cross-checked against `allowedFields` in
 *     `cmd/internal/assistantconfig/config.go`
 *
 * The field sets are read from source, so adding or removing a field without
 * regenerating fails `check:config-schema` with a drift report. The two
 * assistant field sets must also agree; a Go launcher and TypeScript host that
 * accept different keys is a startup-contract bug, not a schema difference.
 *
 * Fail-closed validation remains the runtime authority. This schema only
 * documents the accepted shapes and detects drift; it never relaxes a check.
 *
 * Usage:
 *   bun scripts/generate-config-schema.ts            # write the artifact
 *   bun scripts/generate-config-schema.ts --check    # stale-check (CI/lint)
 *   bun scripts/generate-config-schema.ts --print    # stdout only
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const repositoryRoot = resolve(import.meta.dir, "..");
const controllerSource = resolve(repositoryRoot, "cmd/pixie-web/config.go");
const assistantTsSource = resolve(repositoryRoot, "src/assistant/serve.ts");
const assistantGoSource = resolve(repositoryRoot, "cmd/internal/assistantconfig/config.go");
const artifactPath = resolve(repositoryRoot, "docs/config-schema.json");

const GENERATED_COMMENT = "Code generated by generate-config-schema.ts; DO NOT EDIT.";

type JsonSchema = Record<string, unknown>;

/** Go field type -> JSON Schema scalar/array type. Fail closed on anything else. */
const goTypeToSchema: Readonly<Record<string, JsonSchema>> = {
	"[]string": { type: "array", items: { type: "string" } },
	bool: { type: "boolean" },
	int: { type: "integer" },
	string: { type: "string" },
};

/** Per-field refinements that mirror the runtime validators, keyed by JSON name. */
const controllerRefinements: Readonly<Record<string, JsonSchema>> = {
	port: { minimum: 1, maximum: 65535 },
	mode: { enum: ["controller"] },
};

const assistantFieldSchemas: Readonly<Record<string, JsonSchema>> = {
	schemaVersion: { type: "integer" },
	host: { type: "string", minLength: 1 },
	port: { type: "integer", minimum: 1, maximum: 65535 },
	agentDir: { type: "string", minLength: 1 },
	allowSelfRestart: { type: "boolean" },
};

interface ControllerField {
	readonly name: string;
	readonly schema: JsonSchema;
}

function fail(message: string): never {
	throw new Error(`config-schema: ${message}`);
}

function errorMessage(error: unknown): string {
	return error instanceof Error ? error.message : String(error);
}

function read(path: string): string {
	try {
		return readFileSync(path, "utf8");
	} catch (error) {
		fail(`cannot read ${path}: ${errorMessage(error)}`);
	}
}

/** Parses `type runtimeConfigFile struct { ... }` into JSON-named fields. */
export function parseControllerFields(source: string): ControllerField[] {
	const struct = /type runtimeConfigFile struct \{([\s\S]*?)\n\}/.exec(source);
	if (struct?.[1] === undefined)
		fail("runtimeConfigFile struct not found in cmd/pixie-web/config.go");
	const field = /^\s*(\w+)\s+([A-Za-z0-9_[\].]+)\s+`json:"([^"]+)"`/gm;
	const fields: ControllerField[] = [];
	for (const match of struct[1].matchAll(field)) {
		const goType = match[2] ?? "";
		const name = match[3] ?? "";
		const base = goTypeToSchema[goType];
		if (base === undefined) fail(`unsupported Go field type ${JSON.stringify(goType)} for ${name}`);
		if (fields.some((entry) => entry.name === name)) fail(`duplicate controller field ${name}`);
		fields.push({ name, schema: { ...base, ...controllerRefinements[name] } });
	}
	if (fields.length === 0) fail("runtimeConfigFile struct has no json-tagged fields");
	return fields;
}

function parseQuotedSet(source: string, pattern: RegExp, label: string): string[] {
	const block = pattern.exec(source);
	if (block?.[1] === undefined) fail(`${label} not found`);
	const names = [...block[1].matchAll(/"([^"]+)"/g)]
		.map((match) => match[1])
		.filter((value): value is string => value !== undefined);
	if (names.length === 0) fail(`${label} is empty`);
	const sorted = [...names].sort((a, b) => a.localeCompare(b));
	if (new Set(sorted).size !== sorted.length) fail(`${label} contains duplicate keys`);
	return sorted;
}

export function parseAssistantFields(tsSource: string, goSource: string): string[] {
	const fromTypeScript = parseQuotedSet(
		tsSource,
		/ASSISTANT_CONFIG_FIELDS\s*=\s*new Set\(\[([\s\S]*?)\]\)/,
		"ASSISTANT_CONFIG_FIELDS",
	);
	const fromGo = parseQuotedSet(
		goSource,
		/allowedFields\s*=\s*map\[string\]struct\{\}\{([\s\S]*?)\n\}/,
		"assistant allowedFields",
	);
	if (fromTypeScript.join(",") !== fromGo.join(",")) {
		fail(
			`assistant field sets disagree: TypeScript [${fromTypeScript.join(", ")}] vs Go [${fromGo.join(", ")}]`,
		);
	}
	for (const name of fromTypeScript) {
		if (assistantFieldSchemas[name] === undefined) {
			fail(`assistant field ${JSON.stringify(name)} has no schema entry; update the generator`);
		}
	}
	return fromTypeScript;
}

function parseInteger(source: string, pattern: RegExp, label: string): number {
	const match = pattern.exec(source);
	if (match?.[1] === undefined) fail(`${label} not found`);
	const value = Number(match[1]);
	if (!Number.isSafeInteger(value)) fail(`${label} is not an integer`);
	return value;
}

export interface ConfigSchemaSources {
	readonly controllerSource: string;
	readonly assistantTsSource: string;
	readonly assistantGoSource: string;
}

export function buildConfigSchema(sources: ConfigSchemaSources): JsonSchema {
	const controllerFields = parseControllerFields(sources.controllerSource);
	const assistantFields = parseAssistantFields(
		sources.assistantTsSource,
		sources.assistantGoSource,
	);
	const tsVersion = parseInteger(
		sources.assistantTsSource,
		/ASSISTANT_CONFIG_SCHEMA_VERSION\s*=\s*(\d+)/,
		"ASSISTANT_CONFIG_SCHEMA_VERSION",
	);
	const goVersion = parseInteger(
		sources.assistantGoSource,
		/SchemaVersion\s*=\s*(\d+)/,
		"SchemaVersion",
	);
	if (tsVersion !== goVersion) {
		fail(`assistant schemaVersion disagrees: TypeScript ${tsVersion} vs Go ${goVersion}`);
	}

	const controllerProperties: Record<string, JsonSchema> = {};
	for (const field of controllerFields) controllerProperties[field.name] = field.schema;

	const assistantProperties: Record<string, JsonSchema> = {};
	for (const name of assistantFields) {
		const base = assistantFieldSchemas[name];
		if (base === undefined) fail(`assistant field ${JSON.stringify(name)} has no schema entry`);
		assistantProperties[name] =
			name === "schemaVersion" ? { ...base, const: tsVersion } : { ...base };
	}

	return {
		$schema: "https://json-schema.org/draft/2020-12/schema",
		$id: "https://pixie.local/schemas/config-schema.json",
		$comment: GENERATED_COMMENT,
		title: "Pixie configuration schemas",
		description:
			"Documentation and drift detection for the private Pixie JSON configuration files. Runtime fail-closed validation remains authoritative.",
		$defs: {
			controllerConfig: {
				$comment: "pixie_web --config; controller-only mode rejects agentDir and piExecutable.",
				type: "object",
				additionalProperties: false,
				properties: controllerProperties,
			},
			assistantConfig: {
				$comment: "pixie serve --config; every field is required.",
				type: "object",
				additionalProperties: false,
				required: assistantFields,
				properties: assistantProperties,
			},
		},
	};
}

export function renderConfigSchema(schema: JsonSchema): string {
	return `${JSON.stringify(schema, null, "\t")}\n`;
}

function loadSources(): ConfigSchemaSources {
	return {
		controllerSource: read(controllerSource),
		assistantTsSource: read(assistantTsSource),
		assistantGoSource: read(assistantGoSource),
	};
}

interface DriftLine {
	readonly index: number;
	readonly expected: string | undefined;
	readonly actual: string | undefined;
}

function diff(expected: string, actual: string, limit = 20): string {
	const expectedLines = expected.split("\n");
	const actualLines = actual.split("\n");
	const total = Math.max(expectedLines.length, actualLines.length);
	const lines: string[] = [];
	let shown = 0;
	for (let index = 0; index < total && shown < limit; index += 1) {
		const left = expectedLines[index];
		const right = actualLines[index];
		if (left === right) continue;
		const drift: DriftLine = { index: index + 1, expected: left, actual: right };
		lines.push(`    line ${drift.index}`);
		if (drift.expected !== undefined) lines.push(`      - ${drift.expected}`);
		if (drift.actual !== undefined) lines.push(`      + ${drift.actual}`);
		shown += 1;
	}
	if (shown >= limit) lines.push("    ... diff truncated");
	return lines.join("\n");
}

export function runConfigSchemaCheck(artifact = artifactPath): number {
	const rendered = renderConfigSchema(buildConfigSchema(loadSources()));
	let committed: string;
	try {
		committed = readFileSync(artifact, "utf8");
	} catch {
		console.error(`check:config-schema: FAILED — ${artifact} is missing`);
		console.error("Run `bun run generate:config-schema`.");
		return 1;
	}
	if (committed !== rendered) {
		const label = artifact === artifactPath ? "docs/config-schema.json" : artifact;
		console.error(`check:config-schema: FAILED — ${label} is stale`);
		console.error(diff(rendered, committed));
		console.error("Run `bun run generate:config-schema` and commit the result.");
		return 1;
	}
	console.log("check:config-schema: OK (controller and assistant schemas match their sources)");
	return 0;
}

/** Reads an explicit `--artifact <path>` override, if present. */
function artifactOverride(args: readonly string[]): string | undefined {
	const index = args.indexOf("--artifact");
	if (index < 0) return undefined;
	const value = args[index + 1];
	if (value === undefined || value.startsWith("--")) {
		fail("--artifact requires a path");
	}
	return resolve(value);
}

function main(): number {
	const args = process.argv.slice(2);
	const mode = args[0];
	const rendered = renderConfigSchema(buildConfigSchema(loadSources()));
	if (mode === "--print") {
		process.stdout.write(rendered);
		return 0;
	}
	if (mode === "--check") return runConfigSchemaCheck(artifactOverride(args) ?? artifactPath);
	writeFileSync(artifactPath, rendered);
	console.log(`generate:config-schema: wrote ${artifactPath}`);
	return 0;
}

if (import.meta.main) {
	try {
		process.exit(main());
	} catch (error) {
		console.error(errorMessage(error));
		process.exit(1);
	}
}
