// Package design contains storage primitives for the optional Design module.
// The index is deliberately kept out of the generic JSON store and transport:
// a normalized document can be larger than the 16 MiB metadata ceiling and is
// queried through bounded pages rather than returned as one response.
package design

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"

	"golang.org/x/sys/unix"
)

const (
	// MaxIndexArtifactBytes is the dedicated normalized-index artifact limit.
	MaxIndexArtifactBytes = 64 * 1024 * 1024
	indexCopyBufferSize   = 32 * 1024
)

var documentIDPattern = regexp.MustCompile(`^[A-Za-z0-9_-]{1,128}$`)

// IndexArtifact describes an immutable, validated normalized index. Path is
// generated by this package under the store root; worker-supplied paths are
// never accepted.
type IndexArtifact struct {
	DocumentID string `json:"documentId"`
	Path       string `json:"-"`
	Bytes      int64  `json:"bytes"`
	SHA256     string `json:"sha256"`
}

// IndexStore owns the Design document artifact area. Metadata such as slot.json
// remains the caller's small generic state; index bytes use this path only.
type IndexStore struct {
	root string
}

// NewIndexStore creates the dedicated Design artifact directories.
func NewIndexStore(root string) (*IndexStore, error) {
	if root == "" {
		return nil, errors.New("design artifact root is required")
	}
	absolute, err := filepath.Abs(root)
	if err != nil {
		return nil, fmt.Errorf("resolve design artifact root: %w", err)
	}
	if err := ensureDir(absolute); err != nil {
		return nil, fmt.Errorf("create design artifact root: %w", err)
	}
	if err := ensureDir(filepath.Join(absolute, "documents")); err != nil {
		return nil, fmt.Errorf("create design document root: %w", err)
	}
	if err := ensureDir(filepath.Join(absolute, "staging")); err != nil {
		return nil, fmt.Errorf("create design staging root: %w", err)
	}
	return &IndexStore{root: absolute}, nil
}

// WriteIndex streams one worker result into an immutable index artifact. The
// input is content, never a path, and is bounded before it is retained. The
// normalized output must be one JSON object with no trailing data.
func (s *IndexStore) WriteIndex(ctx context.Context, documentID string, input io.Reader) (IndexArtifact, error) {
	if s == nil || s.root == "" {
		return IndexArtifact{}, errors.New("design artifact store is not configured")
	}
	if !documentIDPattern.MatchString(documentID) {
		return IndexArtifact{}, errors.New("invalid design document id")
	}
	if input == nil {
		return IndexArtifact{}, errors.New("design index input is required")
	}
	if ctx == nil {
		ctx = context.Background()
	}
	stagingRoot := filepath.Join(s.root, "staging")
	if err := rejectSymlinkParents(stagingRoot); err != nil {
		return IndexArtifact{}, err
	}
	stage, err := os.CreateTemp(stagingRoot, "index-*.tmp")
	if err != nil {
		return IndexArtifact{}, fmt.Errorf("stage design index: %w", err)
	}
	stagePath := stage.Name()
	removeStage := true
	defer func() {
		_ = stage.Close()
		if removeStage {
			_ = os.Remove(stagePath)
		}
	}()

	hash := sha256.New()
	writer := io.MultiWriter(stage, hash)
	var size int64
	buffer := make([]byte, indexCopyBufferSize)
	for {
		if err := ctx.Err(); err != nil {
			return IndexArtifact{}, err
		}
		read, readErr := input.Read(buffer)
		if read > 0 {
			size += int64(read)
			if size > MaxIndexArtifactBytes {
				return IndexArtifact{}, fmt.Errorf("design index exceeds the %d-byte artifact limit", MaxIndexArtifactBytes)
			}
			if _, err := writer.Write(buffer[:read]); err != nil {
				return IndexArtifact{}, fmt.Errorf("write design index: %w", err)
			}
		}
		if readErr != nil {
			if errors.Is(readErr, io.EOF) {
				break
			}
			return IndexArtifact{}, fmt.Errorf("read design index: %w", readErr)
		}
	}
	if err := stage.Sync(); err != nil {
		return IndexArtifact{}, fmt.Errorf("sync design index: %w", err)
	}
	if err := stage.Close(); err != nil {
		return IndexArtifact{}, fmt.Errorf("close design index: %w", err)
	}
	if err := validateJSONIndex(stagePath); err != nil {
		return IndexArtifact{}, err
	}

	documentDir := filepath.Join(s.root, "documents", documentID)
	if err := ensureDir(documentDir); err != nil {
		return IndexArtifact{}, fmt.Errorf("create design document directory: %w", err)
	}
	path := filepath.Join(documentDir, "index.json")
	if err := rejectSymlinkParents(path); err != nil {
		return IndexArtifact{}, err
	}
	// A hard link is an atomic no-replace publication on the same filesystem.
	// It also avoids copying the large staged artifact a second time.
	if err := os.Link(stagePath, path); err != nil {
		return IndexArtifact{}, fmt.Errorf("publish design index: %w", err)
	}
	if err := os.Chmod(path, 0o444); err != nil {
		_ = os.Remove(path)
		return IndexArtifact{}, fmt.Errorf("make design index immutable: %w", err)
	}
	directory, openErr := os.Open(documentDir)
	if openErr != nil {
		return IndexArtifact{}, fmt.Errorf("open design index directory for sync: %w", openErr)
	}
	syncErr := directory.Sync()
	_ = directory.Close()
	if syncErr != nil {
		return IndexArtifact{}, fmt.Errorf("sync design index publication: %w", syncErr)
	}
	removeStage = true
	return IndexArtifact{DocumentID: documentID, Path: path, Bytes: size, SHA256: hex.EncodeToString(hash.Sum(nil))}, nil
}

// OpenIndex opens a committed index after checking its generated identity and
// bounded regular-file properties. The caller owns the returned file.
func (s *IndexStore) OpenIndex(documentID string) (*os.File, error) {
	if s == nil || s.root == "" || !documentIDPattern.MatchString(documentID) {
		return nil, errors.New("invalid design document id")
	}
	path := filepath.Join(s.root, "documents", documentID, "index.json")
	if err := rejectSymlinkParents(path); err != nil {
		return nil, err
	}
	info, err := os.Lstat(path)
	if err != nil {
		return nil, err
	}
	if !info.Mode().IsRegular() || info.Size() > MaxIndexArtifactBytes {
		return nil, errors.New("design index artifact is invalid")
	}
	file, err := os.OpenFile(path, os.O_RDONLY|unix.O_NOFOLLOW|unix.O_CLOEXEC, 0)
	if err != nil {
		return nil, err
	}
	openedInfo, statErr := file.Stat()
	if statErr != nil || !os.SameFile(info, openedInfo) {
		_ = file.Close()
		return nil, errors.New("design index artifact changed during open")
	}
	return file, nil
}

func validateJSONIndex(path string) error {
	if err := rejectSymlinkParents(path); err != nil {
		return err
	}
	file, err := os.OpenFile(path, os.O_RDONLY|unix.O_NOFOLLOW|unix.O_CLOEXEC, 0)
	if err != nil {
		return fmt.Errorf("open staged design index: %w", err)
	}
	defer file.Close()
	decoder := json.NewDecoder(io.LimitReader(file, MaxIndexArtifactBytes+1))
	var value map[string]json.RawMessage
	if err := decoder.Decode(&value); err != nil {
		return fmt.Errorf("design index is not valid JSON: %w", err)
	}
	if value == nil {
		return errors.New("design index must be a JSON object")
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		if err == nil {
			return errors.New("design index contains trailing JSON")
		}
		return fmt.Errorf("read staged design index: %w", err)
	}
	return nil
}
